### ISSUE TITLE
Improve naming of Accept headers setting

### ISSUE THREAD

**Issue by wouterbeek** [OpenTriply/YASGUI#104]
In the settings page, Accept headers can be chosen from two dropdown lists.  These are currently labeled "SELECT" and "Graph".  I suggest renaming the former to "ASK / SELECT" and the latter to "CONSTRUCT / DESCRIBE", since these are the SPARQL methods that are supported by the options in the respective lists.

**Comment by LaurensRietveld** [comment]
done!
