### ISSUE TITLE
How to perform a SPARQL 1.1 Update request?

### ISSUE THREAD

**Issue by wouterbeek** [OpenTriply/YASGUI#105]
How does one perform a SPARQL 1.1 Update request?

Let's take the following query:

```sparql
base <https://example.org/>
insert data { 
  <s> <p> <o>
}
```

The setting for `GET` requests should be grayed out, since Update requests can only be sent using `POST`.  The Content-Type header is set to `test/plain;charset=UTF-8`, but this should be either `application/x-www-form-urlencoded` or `application/sparql-update`.

**Comment by LaurensRietveld** [comment]
Are you sure that the content-type of the request is set to text/plain? I think the content type of the response is text/plain, as that matches the accept header (as is configurable here: https://github.com/OpenTriply/YASGUI.YASQE/blob/fd5646e7ab15b040393c212f0a02efa51db55dfa/src/defaults.js#L139).
The response

The issue with the request method is valid. I've updated YASQE. Could you check whether it works?

**Comment by wouterbeek** [comment]
Thanks for the quick fix!  I indeed mistyped in my OP: `test` should be `text`.  Closing...
