### ISSUE TITLE
Enable yasgui.org/shorten for other domains?

### ISSUE THREAD

**Issue by l00mi** [OpenTriply/YASGUI#109]
Is it possible to make the urlshortner of yasgui.org available for other domains? I tried this at http://data.admin.ch/sparql/ and except of a empty answer from yasgui.org it seems to work.

**Comment by LaurensRietveld** [comment]
Just curious: why would you prefer the yasgui shortener over other shortener services?

**Comment by l00mi** [comment]
Ah, there seems to be a miss understanding on my side. Which other services could be used for this?

**Comment by LaurensRietveld** [comment]
There are a few other services such a bit.ly or the google shortener. I tried some of these, but noticed that their use is a bit cumbersome (e.g. not supporting cors, without an API key). 
So, I just removed the cors limitation of the yasgui shortener (see https://github.com/OpenTriply/YASGUI.server/commit/d38f4f69d4a942e6ed9c4a33b26bee30c6479538). I see you're instance works fine now

**Comment by l00mi** [comment]
Genius! Thank you very much.
