### ISSUE TITLE
Configuring the list "catalogueEndpoints"

### ISSUE THREAD

**Issue by mhabsaoui** [OpenTriply/YASGUI#114]
Hi,

is it possible to manually modify the list of "catalogueEndpoints" with a method provided in JavaScript (apart from src code) ?

Thanks.

**Comment by LaurensRietveld** [comment]
Yes, you can modify YASGUI.defaults.catalogueEndpoints before initializing YASGUI . Or were you looking for something else?

**Comment by mhabsaoui** [comment]
No it's what I was looking for :+1:  

So writing in JS "YASGUI.defaults.catalogueEndpoints = [....]" overides the yasgui.min.js" defaults right ?
And also I would like to disable the Edit state of the listbox (from Js / CSS) so it shows only one Endpoint that cannot be modified, is it ok to do so ?

Thanks.

**Comment by mhabsaoui** [comment]
I needed more info but you closed it before me :/
So my questions are in previous post...

Thanks.

**Comment by mhabsaoui** [comment]
Finally found, after some searching, your FULL doc API and so on :
https://gist.github.com/LaurensRietveld/3b490a52700628d16dfc0964518223aa

Why is it missing from Github, maybe adding it on the github wiki tab would be efficient...

**Comment by gpetz** [comment]
Is there still support of YASGUI.defaults.catalogueEndpoints in the current version of Yasgui?
