### ISSUE TITLE
Access problem to @triply dependencies

### ISSUE THREAD

**Issue by bergos** [OpenTriply/YASGUI#121]
@LaurensRietveld It's not possible to install the latest version, because the `@triply/*` dependencies can't be installed. I got redirected to a login screen, when I tried to access the packages in the npm web interface. Maybe the packages only need to be marked public.

**Comment by LaurensRietveld** [comment]
Hi @bergos , thanks for letting me know. These packages weren't needed to build yasgui, but were mistakenly included in the package.json file. The newest version (2.7.22) on npm shouldnt have this issue
