### ISSUE TITLE
Mentioning IOS Press as a data publisher that uses YASGUI

### ISSUE THREAD

**Issue by s-delbecque** [OpenTriply/YASGUI#122]
Hi,

We just launched our linked data portal LD Connect at http://ld.iospress.nl and we are using YASGUI as our Query interface at http://ld.iospress.nl/query-interface/.

We would like to attribute YASGUI, and would like to ask if there is any particular format we should follow?
If possible, it would be great to be included in your list of data publishers in your "Used by many" section in your README.md as well.

Thanks!

Stephanie

**Comment by wouterbeek** [comment]
Hi @s-delbecque,

Thanks for using YASGUI!  I'll add it to the list of publishers in the README file.

If you want to attribute YASGUI on your site, its best to refer to the main YASGUI paper, which was published by IOS Press (Semantic Web Journal): [Rietveld, Laurens, and Rinke Hoekstra. "The YASGUI family of SPARQL clients 1." Semantic Web 8.3 (2017): 373-383.](https://content-iospress-com.vu-nl.idm.oclc.org/articles/semantic-web/sw197)

**Comment by wouterbeek** [comment]
PS: When I download the N-Quads datadump, the file seems to end in the middle of a triple/IRI.  Could it be that the file is only partially uploaded?

**Comment by s-delbecque** [comment]
Hi @wouterbeek 

Thanks!!

Ok, great, we'll refer to the SWJ paper!

Thanks for the feedback of the N-Quads datadump. I tested it on several browsers and devices, without any problem. Could you give me some context of where it went wrong with your download, so we can have a closer look?

Thanks!

**Comment by s-delbecque** [comment]
@wouterbeek 

Both file sizes and lines are correct and last bit got fixed. Will have a look at the macOS files as well!

Thanks for your feedback!
