### ISSUE TITLE
git:// dependency in YASGUI

### ISSUE THREAD

**Issue by ktk** [OpenTriply/YASGUI#123]
We recently couldn't manage to install Trifid at a customers site as one of the YASGUI dependencies has a `git://` dependency in it. Unfortunately this is pretty much impossible to resolve in most company networks, http over proxy is all you get there.

It is [bootstrap-contextmenu](https://github.com/OpenTriply/YASGUI/blob/gh-pages/package.json#L72), would be great if this could be avoided somehow.

**Comment by LaurensRietveld** [comment]
Good point, I've added the npm package as dep now
