### ISSUE TITLE
doc links not working

### ISSUE THREAD

**Issue by sheehan** [OpenTriply/YASGUI#124]
Hi! Noticed some of these links are not working:

http://doc.yasgui.org/
http://yasqe.yasgui.org/
http://yasr.yasgui.org/

![image](https://user-images.githubusercontent.com/253069/42464853-f3c06e14-836f-11e8-88bf-e603d70ee6b3.png)

**Comment by LaurensRietveld** [comment]
Thanks for the fyi @sheehan . Seems I didnt migrate to a new dns registry properly. Fixed now
