### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by co0p** [OpenTriply/YASGUI#126]
Hi,

we would like to use yasgui locally but are currently not able due to the fact that there is no LICENSE file. Please decide on a LICENSE and 

thank you.

**Comment by LaurensRietveld** [comment]
Is there a reason why the `license` key in the package.json file doesnt suffice? (https://github.com/OpenTriply/YASGUI/blob/gh-pages/package.json#L6)

**Comment by co0p** [comment]
hi. Thank you for the response. in the MIT license it says:

....The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software....


which I understand you are currently not doing. I am not an expert on
licensing. I just want to be sure that there is a license.

github also encourages repo owners to include a license file:
https://help.github.com/articles/licensing-a-repository/

but your answer is good enough for me. MIT it is!

cheers, co0p

Laurens Rietveld <notifications@github.com> schrieb am Di., 17. Juli 2018,
20:31:

**Comment by LaurensRietveld** [comment]
Thanks for the extra info. I'll add the licenses next time I'm working on the libs
