### ISSUE TITLE
Make it easy to set up a very compact page (and other ideas)

### ISSUE THREAD

**Issue by alanruttenberg** [OpenTriply/YASGUI#49]
## 
## I'm quickly relating my experiences and brainstorming below in case they might help in further development. Of course I would be happy if you implemented this, but don't want to come off as being ungrateful for your excellent work thus far.

I work with large queries and result sets and so I am sensitive about wasting screen space. I've attached a screenshot of what a page I'm hacking on looks like. However I find it fairly difficult to figure out what things to set. In this I've changed the SPARQL editor font (googles "Source Code Pro"), size and spacing, have made the SPARQL window autosizing (still can't figure out how to set this as default I have to  yasqe.setSize(null,"auto") for each instance) and have changed the result table font size, spacing, and column layout.

I'm hacking this using insertRule(http://davidwalsh.name/add-rules-stylesheets). The settings are below. I'm no javascript/css master, so don't laugh at my stumbling aroung ;-)

This: YASR.plugins.table.defaults.useGoogleCharts=false; is obviously not the way to turn off the google chart. How should I? 

The other interface elements are still larger than they I need them to be.  <div class="yasr_header"> is larger than it needs to be. I love the raw response vs table view but don't need the pivot table or google chart, so a simple checkbox would suffice. Perhaps the search window can be placed up with the tabs.

For the editor it would be nice to have a quick switch to move between autosize and a fixed size editor (with the number of lines when fixed size settable). As I mentioned in another report, folding the PREFIX section would be great. My style is never to use bare URIs in the query, instead defining a prefix with a readable label (our URIs are opaque). So that section can get large. However, if it were possible I would rather have the actual labels (completed) in the sparql query, with the query sent to the endpoint using the URIs.

I've also written an applescript that lets me programmatically send a query to YASGUI - That's nice for development where I'm generating queries in the R environment but can toss them to YASGUI for debugging. I can send this along if you would like.

sheet.insertRule(".yasgui .CodeMirror { position:left!important;font-size:11px!important;line-height:12px!important;font-family:Source Code Pro!important}", 0);
sheet.insertRule(".yasr table.dataTable tr {line-height:1px}",0)
sheet.insertRule(".yasr table.dataTable td { overflow:hidden; text-overflow: ellipsis;white-space: nowrap}",0)
sheet.insertRule(".yasr table.dataTable th sorting {width:auto!important}",0)
sheet.insertRule(".yasr table.dataTable thead tr th {width:auto!important;}",0)
sheet.insertRule(".yasr table.dataTable {width:auto!important;margin-left:0}",0)
sheet.insertRule(".yasgui .controlbar .endpointText {font-size:13px;width:500px!important}",0)

![screen shot 2015-05-04 at 5 47 20 pm](https://cloud.githubusercontent.com/assets/241934/7463559/5597959e-f288-11e4-83f7-4e4176c06fbd.png)

**Comment by LaurensRietveld** [comment]
hi @alanruttenberg , thanks, feedback is appreciated ;).

below some inline comments:

> In this I've changed the SPARQL editor font (googles "Source Code Pro"), size and spacing, have made the SPARQL window autosizing (still can't figure out how to set this as default I have to yasqe.setSize(null,"auto") for each instance) and have changed the result table font size, spacing, and column layout.
About the auto-sizing: I'll add this to the yasqe options (https://github.com/YASGUI/YASQE/issues/63)
About the font: I like the font. I'll add it to the YASQE part of the YASGUI lib (https://github.com/YASGUI/YASGUI/issues/50). I won't add it to the YASQE standalone verison though, as this would introduce a third dependency (next to css/js) for people to include.
About the spacing and column widths: I'll try your configuration out to see the effect on small and large tables. Have to watch out though, as the datatables plugin I use for the table has some smart resizing optimizations, which we'd disable when overwriting these css attributes.

> This: YASR.plugins.table.defaults.useGoogleCharts=false; is obviously not the way to turn off the google chart. How should I?
To disable google chart, set YASR.defaults.useGoogleCharts = false (see http://yasr.yasgui.org/doc/). 

> The other interface elements are still larger than they I need them to be. I love the raw response vs table view but don't need the pivot table or google chart, so a simple checkbox would suffice. Perhaps the search window can be placed up with the tabs.
If you'd like to disable the pivot plugin, you could modify YASR.defaults.outputPlugins (remove 'pivot' from the array)

> For the editor it would be nice to have a quick switch to move between autosize and a fixed size editor (with the number of lines when fixed size settable). 
You should be able to modify the height by dragging the bottom part of the query editor. Is that sufficient? And I'd like to see an option to switch between fixed and dynamic, but would like to do this without interface clutter (as many won't use this option, considering the majority of queries are relatively small).
An option (more of a hidden feature) I'm thinking about is toggle dynamic/static width by single-clicking the bottom border of the query editor (otherwise used for resizing the editor manually via dragging)

> As I mentioned in another report, folding the PREFIX section would be great.
This should be taken care of now. Will integrate this YASQE version in YASGUI soon

>  However, if it were possible I would rather have the actual labels (completed) in the sparql query, with the query sent to the endpoint using the URIs.
More tricky than expected. This needs a proper js SPARQL parser, e.g. https://github.com/RubenVerborgh/SPARQL.js. However, this one isnt included at the moment in YASGUI, and considering the library size I'm a bit hesitant on doing that.

> I've also written an applescript that lets me programmatically send a query to YASGUI - That's nice for development where I'm generating queries in the R environment but can toss them to YASGUI for debugging. I can send this along if you would like.
Not sure how that would look like, so yes, I'd like to have a look at these ;)

**Comment by alanruttenberg** [comment]
>About the spacing and column widths: I'll try your configuration out to see the effect on small and large tables. Have to watch out though, as the datatables plugin I use for the table has some smart resizing optimizations, which we'd disable when overwriting these css attributes.

Actually I change the column layout because the default seemed to have large minimum sizes. Now it resizes each column to just what's needed for display. What I'd prefer would be that URI results have a minimum size that is less than what's needed for their display, and when they overflow it is the left side that is truncated, since the part I'm usually interested in is the last bit. For textual fields, a minimum size again, but also a maximum size beyond which text is wrapped (unless there is room to display it without forcing something off window to the right. Maybe even a maximum height after which overflow is truncated with ellipsis. It's a compromise between being able to see longer text fields and seeing enough rows. In both cases, when overflow, hover shows the full value.

Regarding the applescript, I've included it below.  It is invoked from command line with the first argument being the URL of the editor and the second the name of a file where the sparql is written. Most of the hassle is in quoting. This version tries to accommodate bother graphdb and yasgui. If the front window has YASGUI in the title then it sends the sparql there. Otherwise it assumes that I want graphdb and opens a new editor. It also currently uses "|" as a line separator, fixing that in javascript as I was having trouble working with the newlines. That's suboptimal as "|" can be used in expressions. 

I my dev environment I have a switch that will have queries otherwise executed to be put into the editor instead.

```bash
osascript putsparql.scpt http://127.0.0.1:8080/graphdb-workbench-ee/sparql /tmp/sparql.sparql 2>&1
```

Thanks,
Alan

```applescript
on run argv
	set theurl to (item 1 of argv)
	set thefile to (item 2 of argv)
	--	set thefile to "/tmp/sparql.sparql"
	set AppleScript's text item delimiters to "
"
	set thecontent to text items of (read thefile)
	set whole to ""
	repeat with i from 1 to the count of items of thecontent
		set whole to whole & item i of the thecontent & "|"
	end repeat
	set thecontents to (replaceText(whole, "\"", "\\\"") & "\"" & ".split(\"|\").join(\"\\n\")")
	set thefunction to "if(typeof(window.editor)==\"undefined\") {tab=window.yasgui.addTab();tab.yasqe.setValue(\"" & thecontents & ");tab.yasqe.setSize(null,\"auto\")} else {window.editor.setValue(\"" & thecontents & ")}"
	copy thefunction to stdout
	tell application "Google Chrome"
		if title of active tab of window 1 does not contain "YasGUI" then
			open location theurl
			delay 2
		end if
		tell window 1
			execute active tab javascript (thefunction)
		end tell
	end tell
	thefunction
end run

to replaceText(someText, oldItem, newItem)
	set {tempTID, AppleScript's text item delimiters} to {AppleScript's text item delimiters, oldItem}
	try
		set {itemList, AppleScript's text item delimiters} to {text items of someText, newItem}
		set {someText, AppleScript's text item delimiters} to {itemList as text, tempTID}
	on error errorMessage number errorNumber -- oops
		set AppleScript's text item delimiters to tempTID
		error errorMessage number errorNumber -- pass it on
	end try
	
	return someText
end replaceText
```

**Comment by alanruttenberg** [comment]
>You should be able to modify the height by dragging the bottom part of the query editor. Is that sufficient? And I'd like to see an option to switch between fixed and dynamic, but would like to do this without interface clutter (as many won't use this option, considering the majority of queries are relatively small). An option (more of a hidden feature) I'm thinking about is toggle dynamic/static width by single-clicking the bottom border of the query editor (otherwise used for resizing the editor manually via dragging)

It is sufficient, of course, but my preference is to have the switch. First, the editor won't shrink beyond a certain size, and second I find that I just don't like to scroll as most times, if I'm in the editor, I'm debugging something and it helps to see everything at once.

Putting the control on the bottom bar is clever, but note that it is a very small target and so it isn't fluid to make the change. Another choice would be to hide it in a popup menu inside the editor (with some other options), or use a small icon in the bottom right of the editor. In the interest of less clutter, I wouldn't mind if it faded from view when the mouse is away, as long as the target area is memorable and large enough to easily click. Maybe an icon along the lines of ![facing vertical arrows](https://cdn4.iconfinder.com/data/icons/epic-outlines/30/shrink_vertical-24.png)

**Comment by alanruttenberg** [comment]
>>However, if it were possible I would rather have the actual labels (completed) in the sparql query, with the query sent to the endpoint using the URIs.

>More tricky than expected. This needs a proper js SPARQL parser, e.g. https://github.com/RubenVerborgh/SPARQL.js. However, this one isnt included at the moment in YASGUI, and considering the library size I'm a bit hesitant on doing that.

Hmm, why the need for a sparql parser? I'm thinking that if you ask for label completion and it is successful then the label is inserted into the editor and a property holding the URI added to the span (does codemirror support that?). Then, before sending to the endpoint the marked spans are replaced with their URIs. 

That approach means that you have to do a completion each time - you can't just write the labels, although a completion on text that is already complete doesn't have to pop up the choose a completion menu. Maybe you do the completion again to interpret an already complete string as something that still needs completion (because there are other labels that start with the same string).

An alternative to the span would be to, on recognition of a label, do as I do and create a prefix for the term and substitute the prefix in the query.  That round trips better, though you have to watch out for possible escaping issues (space -> underscore is a given).

**Comment by LaurensRietveld** [comment]
>>You should be able to modify the height by dragging the bottom part of the query editor. Is that sufficient? And I'd like to see an option to switch between fixed and dynamic, but would like to do this without interface clutter (as many won't use this option, considering the majority of queries are relatively small). An option (more of a hidden feature) I'm thinking about is toggle dynamic/static width by single-clicking the bottom border of the query editor (otherwise used for resizing the editor manually via dragging)

>It is sufficient, of course, but my preference is to have the switch. First, the editor won't shrink beyond a certain size, and second I find that I just don't like to scroll as most times, if I'm in the editor, I'm debugging something and it helps to see everything at once.

>Putting the control on the bottom bar is clever, but note that it is a very small target and so it isn't fluid to make the change. Another choice would be to hide it in a popup menu inside the editor (with some other options), or use a small icon in the bottom right of the editor. In the interest of less clutter, I wouldn't mind if it faded from view when the mouse is away, as long as the target area is memorable and large enough to easily click. Maybe an icon along the lines of ![facing vertical arrows](https://cdn4.iconfinder.com/data/icons/epic-outlines/30/shrink_vertical-24.png)

This should be taken care of now (see #51). The resize handler is still a bit too small, but it has been surprisingly tricky to get this larger. I might spend some more time on that later

**Comment by LaurensRietveld** [comment]
>>>However, if it were possible I would rather have the actual labels (completed) in the sparql query, with the query sent to the endpoint using the URIs.

>>More tricky than expected. This needs a proper js SPARQL parser, e.g. https://github.com/RubenVerborgh/SPARQL.js. However, this one isnt included at the moment in YASGUI, and considering the library size I'm a bit hesitant on doing that.

>Hmm, why the need for a sparql parser? I'm thinking that if you ask for label completion and it is successful then the label is inserted into the editor and a property holding the URI added to the span (does codemirror support that?). Then, before sending to the endpoint the marked spans are replaced with their URIs. 

>That approach means that you have to do a completion each time - you can't just write the labels, although a completion on text that is already complete doesn't have to pop up the choose a completion menu. Maybe you do the completion again to interpret an already complete string as something that still needs completion (because there are other labels that start with the same string).

>An alternative to the span would be to, on recognition of a label, do as I do and create a prefix for the term and substitute the prefix in the query.  That round trips better, though you have to watch out for possible escaping issues (space -> underscore is a given). 

Ah, I was completely on the wrong page here. What you'd like is tricky to support, as I can imagine the SPARQL query won't often be syntactically correct right? E.g. when the predicate uri is substituted by a label. 
Could you post a with and without label example of what you'd like to achieve?

**Comment by alanruttenberg** [comment]
> If you'd like to disable the pivot plugin, you could modify YASR.defaults.outputPlugins (remove 'pivot' from the array)

Doesn't seem to be there:
YASR.defaults.outputPlugins
->["table", "error", "boolean", "rawResponse"]

**Comment by LaurensRietveld** [comment]
It seems YASR was drawing all the registered plugins, instead of listening to this option. (i.e., this option was completely ignored).
I've fixed it now (https://github.com/YASGUI/YASR/issues/69). The YASGUI version I just pushed (will be online in a few minutes) has the new YASR version as well

**Comment by LaurensRietveld** [comment]
most of the issues mentioned seem to have been resolved or submitted as other issues. If there are some important issues left open, let me know. Closing this for now
