### ISSUE TITLE
SPARQL protocol violation

### ISSUE THREAD

**Issue by keyoffecka** [OpenTriply/YASGUI#75]
As stated here http://www.w3.org/TR/sparql11-protocol/#query-via-get

Protocol clients may send protocol requests via the HTTP GET method. When using the GET method, clients must URL percent encode all parameters and include them as query parameter strings with the names given above [RFC3986].

While YASGUI does some  other type of encoding. For example

select * where {?s ?p ?o}

is encoded as

select+*+where+%7B%3Fs+%3Fp+%3Fo%7D

while it should be

select%20*%20where%20%7B%3Fs%20%3Fp%20%3Fo%7D

**Comment by LaurensRietveld** [comment]
Thanks for reporting, this issue is now fixed with the newest release of YASQE and YASGUI
