### ISSUE TITLE
Query tab rename fails in firefox 

### ISSUE THREAD

**Issue by apb2006** [OpenTriply/YASGUI#77]
On Firefox 45.0.1 win10. Right click on tab name,select rename..

ReferenceError: event is not defined
http://yasgui.org/dist/yasgui.min.js
Line 40

Works on Chrome

**Comment by LaurensRietveld** [comment]
Jup, I see, thanks. A doubleclick on the tab will workaround this issue, but I'll make sure to fix this button as well

**Comment by LaurensRietveld** [comment]
The newest version (2.1.7) now includes this bugfix
