### ISSUE TITLE
yasgui (yasr) doesn't understand HTTP post response

### ISSUE THREAD

**Issue by sschaef** [OpenTriply/YASGUI#78]
I have my own server, with a SPARQL endpoint and I would like to send queries against it with yasgui. Sending the query works well, but yasgui doesn't understand the query response. I'm wondering if I'm doing something wrong.

When I send a HTTP post request the output looks like this:
```
% curl -v --data 'query=select+*+where+{?s+?p+?o}+limit+1' 'http://localhost:9999/sparql'                                                                                                                          M
*   Trying ::1...
* connect to ::1 port 9999 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST /sparql HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.47.1
> Accept: */*
> Content-Length: 39
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 39 out of 39 bytes
< HTTP/1.1 200 OK
< Server: akka-http/2.4.3
< Date: Thu, 14 Apr 2016 21:39:22 GMT
< Content-Type: application/sparql-results+xml; charset=UTF-8
< Content-Length: 524
<
<?xml version="1.0"?>
<sparql xmlns="http://www.w3.org/2005/sparql-results#">
  <head>
    <variable name="s"/>
    <variable name="p"/>
    <variable name="o"/>
  </head>
  <results>
    <result>
      <binding name="s">
        <uri>http://test.model/_root_/helloWorld</uri>
      </binding>
      <binding name="p">
        <uri>http://www.w3.org/1999/02/22-rdf-syntax-ns#type</uri>
      </binding>
      <binding name="o">
        <uri>http://schema.org/Text</uri>
      </binding>
    </result>
  </results>
</sparql>
* Connection #0 to host localhost left intact
```

Is anything wrong with that? Because yasr doesn't display the result but tells me the following:
```
Resource representation is only available with these types:
application/sparql-results+xml; charset=UTF-8
```
The error message doesn't make any sense to me

**Comment by LaurensRietveld** [comment]
This is indeed a strange error. I tried loading your SPARQL response in YASR as string (via `yasr.setResponse(<string>)`), and that works as expected.
This error does not seem to be thrown by YASR, but by the server.
I saw you use akka, and this ticket seems to be related to the problem you're having: https://github.com/akka/akka/issues/18425

Apparently, there seems to be a accept-header issue here. To debug, I suggest you take the curl request send by the browser (in chrome, open dev toolbar, select network tab, select the sparql request, and select 'copy as curl'), and see whether that curl request throws an error (I suspect it does)

**Comment by sschaef** [comment]
Alright, thanks for investigating this. I couldn't see that the error came from the server side. The curl request from chrome revealed what was wrong. The header `-H 'Accept: application/sparql-results+json'` was passed, but I delivered XML output because I didn't look at the header. After delivering JSON everything works as it should.
