### ISSUE TITLE
Report query evaluation error to YASGUI

### ISSUE THREAD

**Issue by sschaef** [OpenTriply/YASGUI#79]
Right now, not all invalid SPARQL queries are shown as incorrect in YASGUI. For example:
```
select * where { ?s ?p ?o } limit 
```
At the end, an integer is missing. Is there a way to show an error that occurred on the server in YASGUI?

**Comment by LaurensRietveld** [comment]
How the client-side parsing works is that queries that are partially complete and valid considering the partial syntax tree, are marked as valid. 
Are you suggesting to modify this client-side parsing behaviour, or to implement a query validation step in the backend (who's main job atm is proxying the SPARQL queries to the endpoints)?

**Comment by sschaef** [comment]
Actually, this ticket is useless. I just wanted to show an error message to users in case something went wrong on the server. This is easy to accomplish, since the error message of the server is already displayed in YASR.
