### ISSUE TITLE
Code completion failed to fetch suggestions

### ISSUE THREAD

**Issue by sschaef** [OpenTriply/YASGUI#81]
I have the following query:
```
PREFIX s:<http://schema.org/>

select * where {
  ?x s:
}
```

Once I press `CTRL-Space` at the colon it says "Failed fetching suggestions".

What do I have to do to fix this? Do I have to download some ontologies from schema.org and add them to the configuration of YASGUI? Can YASGUI download them manually and if so how can I tell it to do so?

**Comment by LaurensRietveld** [comment]
The ontologies are fetch from the Linked Open Vocabularies api (lov.okfn.org/dataset/lov/api/v2/autocomplete/terms?). The public YASGUI version (yasgui.org) seems to work fine with autocompletions. Do you have a running public instance that I can check out?

ps.  I suggest you check the network tab on the developer toolbar, to see whether the autocompletion request is send, and whether it returns an error

**Comment by sschaef** [comment]
It turned out it is a browser issue. It works on Chromium but not on Firefox (45+). In Firefox, no network requests are shown at all in the network tab of the developer toolbar.

**Comment by LaurensRietveld** [comment]
My firefox (46) seems to work fine. Did you test this on the YASGUI version at yasgui.org as well? (preferably in a private window, to avoid caching issues)

**Comment by sschaef** [comment]
Ok, it was a caching issue. In the private window everything worked fine and after removing the site from the cache it works fine in a normal tab. Thanks for help.

**Comment by LaurensRietveld** [comment]
great, good to hear

**Comment by sschaef** [comment]
Oh, btw is it possible to add more endpoints for the code completion? I have my own ontologies which are not yet public and I don't want to make them public yet because they still change a lot. I don't know if the site, which you linked above, allows to change the ontologies often.

**Comment by LaurensRietveld** [comment]
are these ontologies in the endpoint you're querying? If so, you should be able to query for them yourself by registering your own autocompleters. See this gist for an example: 
https://gist.github.com/LaurensRietveld/3549c02f5727346ae89c (you'd have to change the actual query though. this one expects a particular dataset description)
