### ISSUE TITLE
feature request: auto-fill of ontology c,a] and descriptions

### ISSUE THREAD

**Issue by rlzijdeman** [OpenTriply/YASGUI#83]
Hi, for me a great feature of YASGUI is that it adds the full URI of an ontology, once you type its prefix in the query. I was wondering whether a similar feature could be implemented listing and describing the different 'properties' of a vocabulary, i.e. if you would type dbo: it would provide you a list with 'agent', 'place', and the descriptions of what they mean (e.g. their rdfs:label). I got this idea from the latest version of [Rstudio](https://www.rstudio.com) which provides a feature like that for their functions (see examples below).

I have no idea what I'm asking for in terms of feasibility or effort so 'go ask Santa' seems to be a descent reply :P 

# Examples
Once you type a few characters and hit tab, R provides a menu with all available functions starting with those characters:

<img width="662" alt="rstudiotabsummonsfunctions" src="https://cloud.githubusercontent.com/assets/3480446/18943262/c19b50de-861e-11e6-8472-4d5eb7a66c77.png">

Once you selected a command and hit tab once more it provides you the options of the function.
<img width="564" alt="rstudiotabsummonsfunctionoptions" src="https://cloud.githubusercontent.com/assets/3480446/18943261/c16627b0-861e-11e6-8cfc-89f5f09ab243.png">

Similarly typing 'db' might give you a list of prefixes like 'dbo' and upon selection, hitting tab once more, might give you the dbo classes and their rdfs:label's.

**Comment by LaurensRietveld** [comment]
As discussed, auto-completion for properties and classes is already supported (via the LOV api)
