### ISSUE TITLE
Prefix-generation bugged with Firefox

### ISSUE THREAD

**Issue by pchampin** [OpenTriply/YASGUI#84]
Since recently, I have a problem when using yasgui.org in Firefox (50.0b5, Ubuntu): whenever I enter an undeclared prefix (e.g. owl:), yasgui freezes, and after a while I get an "Unresponsive script" dialog prompting me to stop the script. Then I reload the page, and I see hundreds of lines "PREFIX owl: <http://www.w3.org/2002/07/owl#>" at the top of the query...

I do not have that problem on Chrome, but I still have it with a fresh Firefox profile, so it is not due to some extension in my profile.

**Comment by LaurensRietveld** [comment]
Thanks for the report. This seemed to have been an issue in all browsers. The newest YASQE release is now fixed, I'll make sure to update the YASGUI version as well.
