### ISSUE TITLE
compilation errors when using via npm/browserify

### ISSUE THREAD

**Issue by jameslaneconkling** [OpenTriply/YASGUI#85]
I'm getting two compilation errors when I install via npm and package via browserify:
```
 module not found:
"selectize" from file /Users/james/Documents/Projects/sparql-dashboard/node_modules/yasgui/src/jquery/endpointCombi.js 
```
and
```
 Cannot find module 'browserify-shim' from '/Users/james/Documents/Projects/sparql-dashboard/node_modules/yasgui-yasr' 
```

**start edit**
my bad--unrelated error b/c I was trying to attach yasgui to a dom node before the node was created...
~~Have tried to build locally and link into my project to see if I can't debug, which doesn't throw compilation errors, but throws another selectize error at runtime:
`endpointCombi.js:180 Uncaught TypeError: Cannot read property 'selectize' of undefined(…)`at [here](https://github.com/OpenTriply/YASGUI/blob/gh-pages/src/jquery/endpointCombi.js#L180).~~
**end edit**

The selectize dependency points to an old version of selectize `git://github.com/brianreavis/selectize.js`, but updating does not actually solve the issue.

Any advice on getting this running via npm?  Thanks.

**Comment by jameslaneconkling** [comment]
I forked the project and repointed selectize to the current master branch and it solved the first compilation bug.  Will submit a PR, in case that's helpful.

Still getting the second compilation error, which looks like it's coming from the upstream [yasgui-yasr](https://github.com/OpenTriply/YASGUI.YASR/blob/gh-pages/package.json) project.  Installing `browserify-shim` as a dev dependency works as a temporary fix.

**Comment by LaurensRietveld** [comment]
I think the problem with `browserify-shim` is the following: this lib is used in the YASGUI/YASR/YASQE as dev dependency, and are therefore not installed when using YASGUI itself as dependency. 
When you include these 3 libs via browserify, it checks the package.json, sees the browsery-shim config, and try to load browserify-shim. It's not installed though, as dev dependencies are not installed recursively. 
Only way I see how to make this work is simply adding browserify-shim as regular dep for all the libraries

**Comment by LaurensRietveld** [comment]
I've pushed a new version of YASGUI with these fixes. If there are any other issues, let me know ;)
