### ISSUE TITLE
yasgui.org no longer working with Fuseki on localhost

### ISSUE THREAD

**Issue by osma** [OpenTriply/YASGUI#88]
I'm used to running SPARQL queries on yasgui.org against Fuseki running on localhost:3030. With Fuseki 1 this used to work out of the box (it is CORS-enabled), with Fuseki 2 you need to do a little bit of configuration to enable CORS.

However, this seems no longer to be working. Looking at browser network access when submitting a query on yasgui.org, the request goes to http://yasgui.org/proxy/ which naturally cannot access my localhost and the UI just gets stuck for a while and then reports an error.

I can still use legacy.yasgui.org this way, it has no problems connecting to Fuseki on localhost. I remember it used to work also on the new UI at yasgui.org at some point. It seems to me that there is not even an attempt to connect to http://localhost:3030 (I watched the network traffic on localhost using ngrep), but the request goes directly to the proxy. The problem is not that localhost wouldn't be CORS-enabled, since it works using legacy.yasgui.org.

My browser is Firefox 49 running on Ubuntu Linux 16.04.

**Comment by LaurensRietveld** [comment]
Thanks for the thorought bug report. I can't reproduce it though. I installed and ran the latest fuseki (2.4.1). I didn't have to change any CORS settings in fuseki, and YASGUI seems to work fine.

Its strange that there is not even one connection made to the fuseki, as YASGUI issues a simple ASK query (on-page-load) to check whether an endpoint is CORS enabled. You could try to open the browser dev toolbar, and refresh the YASGUI page. I'd be interested in what the network tab shows.

One other thing that occurs to me: if you are using YASGUI via https, then the browser will forbid any js connections to http, forcing YASGUI to use the proxy.

**Comment by osma** [comment]
Here is what the network tab shows.
![yasgui-proxy](https://cloud.githubusercontent.com/assets/1132830/20604756/b5ac5f42-b270-11e6-9c15-b6f27d1c6007.png)

I think I may have found the cause...the ASK query that you mentioned is using a URL like `http://localhost:3030/ds/sparql&query=ASK...` - notice the `&` instead of `?`. At least the Fuseki version I'm currently running (1.3.0 that is bundled with hdt-java) gives a 404 error on this, which probably makes YASGUI think that it's not CORS enabled when really the problem is the URL that was used for the checking.

**Comment by osma** [comment]
FYI, the reason I didn't see the ASK query with ngrep was probably that it was made so early, I wasn't watching when it happened.

**Comment by LaurensRietveld** [comment]
Ah, that's a silly bug. I'll update that check, but I don't think it explains this bug though. The ajax response is processed like this: `yasgui.corsEnabled[endpoint] = jqXHR.status > 0;`. I.e., any status code higher than zero is considered cors enabled (because a cors disabled endpoint won't give back a status code).
Could you run this in the browser console? `yasgui.corsEnabled`. I'd be interested in knowing whether YASGUI determined it to be cors-enabled or not

**Comment by LaurensRietveld** [comment]
I've pushed the cors-check fix (online at yasgui.org as well), so you could check whether that was indeed the culprit

**Comment by osma** [comment]
It says:
```js
Object { http://dbpedia.org/sparql=true,  http://localhost:3030/ds/sparql=false}
```

I used a private browsing window for this, just in case, which meant that YASGUI defaults to the dbpedia endpoint (and gets a 404 response from there as well as can be seen from the screenshot I posted above). Then when I change the endpoint URL it makes another request, this time to localhost.

...while I was writing this you did the change, and now it is working for me!

**Comment by osma** [comment]
I have no idea why the dbpedia 404 response worked, while the localhost 404 response didn't, but all is well now, thanks!

**Comment by LaurensRietveld** [comment]
Ah, good to know its resolved! Its a bit of a mystery to me why, but as longs as it works...  ;)

**Comment by osma** [comment]
Maybe Fuseki doesn't issue CORS headers for 404 responses, while dbpedia does, or something like that...

**Comment by LaurensRietveld** [comment]
must be something like that indeed, though the fuseki instance with default settings worked for me

**Comment by osma** [comment]
Fuseki1 and Fuseki2 have different HTTP layers, probably that's why they behave differently
