### ISSUE TITLE
Provide a minimal HTML page

### ISSUE THREAD

**Issue by jmvanel** [OpenTriply/YASGUI#91]
The provided index.html is too big to be integrated as is in an RDF web application.
All is needed is a new HTML yasgui.html with:
- link to the YASGUI project,
- the input field for the query, 
- and the zone for results.

Also convenient would be an HTML parameter to set the SPARQL endpoint, like:
`/yasgui.html?endpoint=http://localhost:9000/sparql`

**Comment by jmvanel** [comment]
What is in view-source:http://yasgui.org/ is perfect.

Is there a way to set the SPARQL endpoint client side ?

**Comment by LaurensRietveld** [comment]
I've just added an example on the yasgui doc page: http://yasgui.org/doc/.
That one should work fine. 

ps. in this gist, YASGUI version 2.5.0 is used. For now, just replace it with 2.4.6 instead, as the latest version still needs to propagate to the jsdelivr CDN. (2.5.0 contains a bugfix that resolves setting the SPARQL endpoint via a YASGUI constructor argument)

**Comment by LaurensRietveld** [comment]
in 2.4.6, if you'd like to change the SPARQL endpoint, just make sure you set `YASGUI.defaults.yasqe.sparql.endpoint = 'someotherendpoint'`

**Comment by jmvanel** [comment]
Opening the URL
http://yasgui.org/?endpoint=http%3A%2F%2Flocalhost%3A9000%2Fsparql
in a fresh browser tab does not change the default endpoint dbpedia as I would expect
( in Chromium )

Is it that the site is not yet updated with the latest code ?

**Comment by LaurensRietveld** [comment]
Ah, that part of the request did not make it in YASGUI. Two reasons:
- The behaviour is unclear of listening to the endpoint argument. What do you expect? A YASGUI tab opening for this particular endpoint, or modifying the currently opened tab? The latter would be undesirable, as you could possibly overwrite existing (saved) queries
- For your own deployment, you could add this yourself. E.g., if you want to initialize yasgui with an endpoint, use something like this: 
```
function getEndpointFromUrl() {
//some code herre to get the endpoint value from window.location.search
}
var yasgui = new YASGUI({
  yasqe: {
    sparql:{
      endpoint: getEndpointFromUrl()
    }
  }
})
```

**Comment by LaurensRietveld** [comment]
closing for now. If there are other issues, let me know

**Comment by jmvanel** [comment]
Sorry that my need was not clear.

In the page
http://semantic-forms.cc:9111/tools
there is a link to yasgui that tries to set the endpoint and query:
http://yasgui.org/?endpoint=http%3A%2F%2Flocalhost%3A9000%2Fsparql,query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT+*+WHERE+%7B+graph+%3Fg+%7B%0A++%3Fsub+%3Fpred+%3Fobj+.%0A%7D%7D+LIMIT+3

but neither of endpoint and query are set in the resulting yasgui page.
