### ISSUE TITLE
Geo button does not work

### ISSUE THREAD

**Issue by ktk** [OpenTriply/YASGUI#92]
I can't seem to get the Geo-button to work on Yasgui. Once I execute the first query the button grays out and I can't do anything with it.

[Sample query](http://web-ld-trifid.dev.bgdi.ch/sparql/#query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT+*+WHERE+%7B%0A++%3Chttps%3A%2F%2Fld.geo.admin.ch%2Fboundaries%2Fcantons%2Fgeometry%2F5%3A2016%3E+%3Fpred+%3Fobj+.%0A%7D+%0ALIMIT+10&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fweb-sparql-virtuoso.dev.bgdi.ch%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&outputFormat=leaflet)

Any ideas what's going wrong here?

**Comment by p1d1d1** [comment]
It does work.

[Sample query 1](http://web-ld-trifid.dev.bgdi.ch/sparql/#query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+geo%3A%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E%0A%0ASELECT+%3Fwkt+WHERE+%7B%0A++%3Chttps%3A%2F%2Fld.geo.admin.ch%2Fboundaries%2Fcantons%2F5%3A2016%3E+geo%3AhasGeometry+%3Fgeom+.%0A++%3Fgeom+geo%3AasWKT+%3Fwkt+.%0A%7D+&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fweb-sparql-virtuoso.dev.bgdi.ch%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&outputFormat=leaflet)

Alternatively if you want to use directly the geometry URI:

[Sample query 2](http://web-ld-trifid.dev.bgdi.ch/sparql/#query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+geo%3A%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E%0ASELECT+%3Fwkt+WHERE+%7B%0A++%3Chttps%3A%2F%2Fld.geo.admin.ch%2Fboundaries%2Fcantons%2Fgeometry%2F5%3A2016%3E+geo%3AasWKT+%3Fwkt+.%0A%7D+&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fweb-sparql-virtuoso.dev.bgdi.ch%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&outputFormat=leaflet)

**Comment by ktk** [comment]
Oh thanks for the hint. Then I would propose to change the behavior of the button. I understood it in a way that something fails but instead I did the wrong query.

**Comment by p1d1d1** [comment]
Don't think there is something wrong with the button.
You just need to set the right query, an in the examples.

**Comment by ktk** [comment]
Ok tnx. @bergos told me there was an error message in the console for a while but I can't find that anymore so I guess there was a bug and it did get fixed meanwhile. Closing it.
