### ISSUE TITLE
Cannot rename a tab in Firefox

### ISSUE THREAD

**Issue by wouterbeek** [OpenTriply/YASGUI#93]
When a tab is renamed the tab visually disappears.  Clicking somewhere else in the screen makes the tab reappear.  Tested on FF51.

**Comment by LaurensRietveld** [comment]
Strange, on my computer FF 51.0.1 works fine. Could you try in a private window?

**Comment by wouterbeek** [comment]
@LaurensRietveld I have the exact same FF version.  However, the problem does not occur when there is only one tab.  Can you try this one more time on http://yasgui.org/ with two tabs open and then double clicking on the first tab (from the left).  The second or last tab does not show the incorrect behavior.

**Comment by LaurensRietveld** [comment]
Could reproduce the issue (in other browsers as well). This is now resolved
