### ISSUE TITLE
'Set editor full screen' does not work in map view

### ISSUE THREAD

**Issue by wouterbeek** [OpenTriply/YASGUI#95]
When YASR is in map view (and there is at least one result), then the 'Set editor full screen' button on the YASQE component no longer works (see attachement).

Reproduced in Chrome and Firefox.

![screenshot from 2017-03-23 11-17-48](https://cloud.githubusercontent.com/assets/1685012/24243227/a75d50ca-0fba-11e7-9df9-e70a3a2e1234.png)

**Comment by LaurensRietveld** [comment]
should be fixed now
