### ISSUE TITLE
SPARQL construct queries

### ISSUE THREAD

**Issue by bertvannuffelen** [OpenTriply/YASGUI#99]
Hi,

SPARQL construct queries yield silent swallow of the respons due to mismatched respons expectations.

On the SPARQL endpoint of dbpedia , using yasgui.org

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
construct { ?obj ?p ?o }  WHERE {
  ?sub a ?obj .
  ?obj ?p ?o.
} 
LIMIT 100
```

I get the error message in my console:

XML Parsing Error: not well-formed
Location: http://yasgui.org/
Line Number 1, Column 1:  yasgui.org:1:1

kr,

Bert

**Comment by wouterbeek** [comment]
I cannot reproduce this issue.  I get a successful result (see screenshot).

![screenshot from 2017-06-20 15-52-53](https://user-images.githubusercontent.com/1685012/27336672-94b5beec-55d0-11e7-8654-e58a6dbc0b7b.png)

@bertvannuffelen Please reopen with another MWE if you believe the issue persist.
